#!/bin/bash

printf "🎸 Convert WAV to MP3\n\n"

if [[ -z "$1" ]]; then
  printf "👹 Oops! Failed wav to mp3 conversion missing the input wav file and output mp3 arguments.\n\n"

  exit 1
fi;

printf "Wav is path is %s\n" "$1"
printf "Mp3 is %s\n\n\n" "$2"

path_to_wav_file=$1
path_to_mp3_output=$2

ffmpeg -i "$path_to_wav_file" \
  -ab 320k \
  -ac 2 \
  -ar 44100 \
  -joint_stereo 0 \
  "$path_to_mp3_output"